import type { Provider, ProviderModel, ModelFetchStrategy } from "@/types";

export const PROVIDERS: Record<string, Provider> = {
  openai: {
    id: "openai",
    name: "OpenAI",
    logo: "🟢",
    baseURL: "https://api.openai.com/v1",
    modelsEndpoint: "https://api.openai.com/v1/models",
    modelFetchStrategy: "openai-compat" as ModelFetchStrategy,
    apiKeyPlaceholder: "sk-...",
    apiKeyPrefix: "sk-",
    docsURL: "https://platform.openai.com/api-keys",
    freeModelsAvailable: false,
    supportsSystemPrompt: true,
  },
  anthropic: {
    id: "anthropic",
    name: "Anthropic",
    logo: "🟣",
    baseURL: "https://api.anthropic.com/v1",
    modelsEndpoint: null,
    modelFetchStrategy: "hardcoded" as ModelFetchStrategy,
    hardcodedModels: [
      { id: "claude-opus-4-5", label: "Claude Opus 4.5" },
      { id: "claude-sonnet-4-5", label: "Claude Sonnet 4.5" },
      { id: "claude-haiku-4-5-20251001", label: "Claude Haiku 4.5" },
    ],
    apiKeyPlaceholder: "sk-ant-...",
    apiKeyPrefix: "sk-ant-",
    docsURL: "https://console.anthropic.com/keys",
    freeModelsAvailable: false,
    supportsSystemPrompt: true,
  },
  google: {
    id: "google",
    name: "Google Gemini",
    logo: "🔵",
    baseURL: "https://generativelanguage.googleapis.com/v1beta/openai",
    modelsEndpoint: "https://generativelanguage.googleapis.com/v1beta/models",
    modelFetchStrategy: "google" as ModelFetchStrategy,
    apiKeyPlaceholder: "AIza...",
    docsURL: "https://aistudio.google.com/app/apikey",
    freeModelsAvailable: true,
    supportsSystemPrompt: true,
  },
  groq: {
    id: "groq",
    name: "Groq",
    logo: "⚡",
    baseURL: "https://api.groq.com/openai/v1",
    modelsEndpoint: "https://api.groq.com/openai/v1/models",
    modelFetchStrategy: "openai-compat" as ModelFetchStrategy,
    apiKeyPlaceholder: "gsk_...",
    apiKeyPrefix: "gsk_",
    docsURL: "https://console.groq.com/keys",
    freeModelsAvailable: true,
    supportsSystemPrompt: true,
  },
  nvidia: {
    id: "nvidia",
    name: "NVIDIA NIM",
    logo: "🟩",
    baseURL: "https://integrate.api.nvidia.com/v1",
    modelsEndpoint: "https://integrate.api.nvidia.com/v1/models",
    modelFetchStrategy: "openai-compat" as ModelFetchStrategy,
    apiKeyPlaceholder: "nvapi-...",
    apiKeyPrefix: "nvapi-",
    docsURL: "https://build.nvidia.com",
    freeModelsAvailable: true,
    supportsSystemPrompt: true,
  },
  openrouter: {
    id: "openrouter",
    name: "OpenRouter",
    logo: "🔀",
    baseURL: "https://openrouter.ai/api/v1",
    modelsEndpoint: "https://openrouter.ai/api/v1/models",
    modelFetchStrategy: "openai-compat" as ModelFetchStrategy,
    apiKeyPlaceholder: "sk-or-...",
    apiKeyPrefix: "sk-or-",
    docsURL: "https://openrouter.ai/keys",
    freeModelsAvailable: true,
    supportsSystemPrompt: true,
    extraHeaders: (apiKey: string) => ({
      "HTTP-Referer": "https://specsplit.ladestack.in",
      "X-Title": "SpecSplit",
    }),
  },
  together: {
    id: "together",
    name: "Together AI",
    logo: "🤝",
    baseURL: "https://api.together.xyz/v1",
    modelsEndpoint: "https://api.together.xyz/v1/models",
    modelFetchStrategy: "openai-compat" as ModelFetchStrategy,
    apiKeyPlaceholder: "...",
    docsURL: "https://api.together.ai/settings/api-keys",
    freeModelsAvailable: true,
    supportsSystemPrompt: true,
  },
  mistral: {
    id: "mistral",
    name: "Mistral AI",
    logo: "🌪️",
    baseURL: "https://api.mistral.ai/v1",
    modelsEndpoint: "https://api.mistral.ai/v1/models",
    modelFetchStrategy: "openai-compat" as ModelFetchStrategy,
    apiKeyPlaceholder: "...",
    docsURL: "https://console.mistral.ai/api-keys",
    freeModelsAvailable: false,
    supportsSystemPrompt: true,
  },
  deepseek: {
    id: "deepseek",
    name: "DeepSeek",
    logo: "🐋",
    baseURL: "https://api.deepseek.com/v1",
    modelsEndpoint: "https://api.deepseek.com/models",
    modelFetchStrategy: "openai-compat" as ModelFetchStrategy,
    apiKeyPlaceholder: "sk-...",
    docsURL: "https://platform.deepseek.com/api_keys",
    freeModelsAvailable: false,
    supportsSystemPrompt: true,
  },
  xai: {
    id: "xai",
    name: "xAI (Grok)",
    logo: "✖️",
    baseURL: "https://api.x.ai/v1",
    modelsEndpoint: "https://api.x.ai/v1/models",
    modelFetchStrategy: "openai-compat" as ModelFetchStrategy,
    apiKeyPlaceholder: "xai-...",
    apiKeyPrefix: "xai-",
    docsURL: "https://console.x.ai",
    freeModelsAvailable: false,
    supportsSystemPrompt: true,
  },
  zencode: {
    id: "zencode",
    name: "OpenCode Zen",
    logo: "🧘",
    baseURL: "https://opencode.ai/zen/v1",
    modelsEndpoint: "https://opencode.ai/zen/v1/models",
    modelFetchStrategy: "openai-compat" as ModelFetchStrategy,
    apiKeyPlaceholder: "Your Zen API key",
    docsURL: "https://opencode.ai/auth",
    freeModelsAvailable: true,
    supportsSystemPrompt: true,
  },
  ollama: {
    id: "ollama",
    name: "Ollama (Local)",
    logo: "🦙",
    baseURL: "http://localhost:11434/v1",
    modelsEndpoint: "http://localhost:11434/api/tags",
    modelFetchStrategy: "hardcoded" as ModelFetchStrategy,
    hardcodedModels: [
      { id: "llama3.2", label: "Llama 3.2" },
      { id: "mistral", label: "Mistral" },
      { id: "codellama", label: "Code Llama" },
      { id: "gemma2", label: "Gemma 2" },
    ],
    apiKeyPlaceholder: "ollama (no key needed)",
    docsURL: "https://ollama.com",
    freeModelsAvailable: true,
    supportsSystemPrompt: true,
  },
};

export const PROVIDER_LIST: Provider[] = Object.values(PROVIDERS);

export function getCategoryColor(category: string): string {
  const colorMap: Record<string, string> = {
    auth: "bg-blue-500",
    backend: "bg-purple-500",
    frontend: "bg-green-500",
    database: "bg-yellow-500",
    devops: "bg-orange-500",
    other: "bg-gray-500",
  };
  return colorMap[category] || "bg-gray-500";
}